import type { Metadata } from "next";
import "../globals.css";
import LeftSidebar from '../components/leftsidebar';
import RightSidebar from '../components/rightsidebar';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex min-h-screen">
          <div className="w-1/4">
            <LeftSidebar />
          </div>
          <div className="w-1/2">
            {children}
          </div>
          <div className="w-1/4">
            <RightSidebar />
          </div>
        </div>
      </body>
    </html>
  );
}
